"""Create actions table

Revision ID: 0f73f3400248
Revises: 0fe5924e0d64
Create Date: 2026-05-10 15:15:04.309003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f73f3400248'
down_revision: Union[str, Sequence[str], None] = '0fe5924e0d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.Enum('send_reply', 'calendar_event', 'job_apply', name='actiontype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'executed', 'approved', 'awaiting_approval', 'rejected', 'failed', name='actionstatus'), nullable=False),
    sa.Column('payload', sa.JSON()),
    sa.Column('result', sa.JSON()),
    sa.Column('error', sa.String()),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actions')
    # ### end Alembic commands ###
