"""Add category column

Revision ID: 0fe5924e0d64
Revises: cfc367837e38
Create Date: 2026-05-10 00:54:08.618393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe5924e0d64'
down_revision: Union[str, Sequence[str], None] = 'cfc367837e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('category', sa.Enum('apply', 'interview', 'reply_needed', 'ignore', name='messagecategory'), nullable=True))
    op.add_column('messages', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('model_reasoning', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'model_reasoning')
    op.drop_column('messages', 'confidence_score')
    op.drop_column('messages', 'category')
    # ### end Alembic commands ###
