"""Add status and body_markdown columns

Revision ID: cfc367837e38
Revises: 0d7731112bb6
Create Date: 2026-05-09 16:03:17.701648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc367837e38'
down_revision: Union[str, Sequence[str], None] = '0d7731112bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body_markdown', sa.String(), nullable=False))
    op.add_column('messages', sa.Column('status', sa.Enum('fetched', 'classified', 'planned', 'actioned', 'failed', name='messagestatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'status')
    op.drop_column('messages', 'body_markdown')
    # ### end Alembic commands ###
